### ISSUE TITLE
"Internal error" Message when incorrect warp name used

### ISSUE THREAD

**Issue by Ilinalta** [RunsWithShovels/WarpControl#1]
Hi, plugin operates very well, only issue I have now is a cosmetic issue. 
When a player does /warp [warpname] using a name that doesn't exist, they get the message 
http://prntscr.com/h9jvhm
I was wondering if an additional message could be added that says "This warp does not exist!" if the warp they've entered doesn't exist, in place of that message. Many thanks

**Comment by JayDeDoubleU** [comment]
Thanks for the information. I thought I had put that condition in the original, guess not. Here is the latest version, with the update.

https://github.com/RunsWithShovels/WarpControl/releases/tag/1.0.0

Also you will need to either delete your current messages.yml file or add the message 'warp-not-exist' to your current one.
